//
//  TVShowCatalog.swift
//  BingeWatchingTracker
//
//  Created by alfredo on 1/12/20.
//  Copyright © 2020 TeamFlash. All rights reserved.
//

import Foundation

struct TVShowCatalog{
    let tvShowCatalog: [Show] = [
    Show(name: "Arrow", favorite: false, episodes: [[
        Episode(name: "Pilot", binged: false),
        Episode(name: "Honor Thy Father", binged: false),
        Episode(name: "Lone Gunmen", binged: false),
        Episode(name: "An Innocent Man", binged: false),
        Episode(name: "Damaged", binged: false),
        Episode(name: "Legacies", binged: false),
        Episode(name: "Muse of Fire", binged: false),
        Episode(name: "Vendetta", binged: false),
        Episode(name: "Year's End", binged: false),
        Episode(name: "Burned", binged: false),
        Episode(name: "Trust But Verify", binged: false),
        Episode(name: "Vertigo", binged: false),
        Episode(name: "Betrayal", binged: false),
        Episode(name: "The Odyssey", binged: false),
        Episode(name: "Dodger", binged: false),
        Episode(name: "Dead to Rights", binged: false),
        Episode(name: "The Huntress Returns", binged: false),
        Episode(name: "Salvation", binged: false),
        Episode(name: "Unfinished Business", binged: false),
        Episode(name: "Home Invasion", binged: false),
        Episode(name: "The Undertaking", binged: false),
        Episode(name: "Darkness on the Edge of Town", binged: false),
        Episode(name: "Sacrifice", binged: false)
        ],
        [
        Episode(name: "City of Heroes", binged: false),
        Episode(name: "Identity", binged: false),
        Episode(name: "Broken Dolls", binged: false),
        Episode(name: "Crucible", binged: false),
        Episode(name: "League of Assassins", binged: false),
        Episode(name: "Keep Your Enemies Closer", binged: false),
        Episode(name: "State v. Queen", binged: false),
        Episode(name: "The Scientist", binged: false),
        Episode(name: "Three Ghosts", binged: false),
        Episode(name: "Blast Radius", binged: false),
        Episode(name: "Blind Spot", binged: false),
        Episode(name: "Tremors", binged: false),
        Episode(name: "Heir to the Demon", binged: false),
        Episode(name: "Time of Death", binged: false),
        Episode(name: "The Promise", binged: false),
        Episode(name: "Suicide Squad", binged: false),
        Episode(name: "Birds of Prey", binged: false),
        Episode(name: "Deathstroke", binged: false),
        Episode(name: "The Man Under the Hood", binged: false),
        Episode(name: "Seeing Red", binged: false),
        Episode(name: "City of Blood", binged: false),
        Episode(name: "Streets of Fire", binged: false),
        Episode(name: "Unthinkable", binged: false)
        ],
        [
        Episode(name: "The Calm", binged: false),
        Episode(name: "Sara", binged: false),
        Episode(name: "Corto Maltese", binged: false),
        Episode(name: "The Magician", binged: false),
        Episode(name: "The Secret Origin of Felicity Smoak", binged: false),
        Episode(name: "Guilty", binged: false),
        Episode(name: "Draw Back Your Bow", binged: false),
        Episode(name: "The Brave and the Bold", binged: false),
        Episode(name: "The Climb", binged: false),
        Episode(name: "Left Behind", binged: false),
        Episode(name: "Midnight City", binged: false),
        Episode(name: "Uprising", binged: false),
        Episode(name: "Canaries", binged: false),
        Episode(name: "The Return", binged: false),
        Episode(name: "Nanda Parbat", binged: false),
        Episode(name: "The Offer", binged: false),
        Episode(name: "Suicidal Tendencies", binged: false),
        Episode(name: "Public Enemy", binged: false),
        Episode(name: "Broken Arrow", binged: false),
        Episode(name: "The Fallen", binged: false),
        Episode(name: "Al Sah-him", binged: false),
        Episode(name: "This Is Your Sword", binged: false)
        ],
        [
        Episode(name: "My Name Is Oliver Queen", binged: false),
        Episode(name: "Green Arrow", binged: false),
        Episode(name: "The Candidate", binged: false),
        Episode(name: "Restoration", binged: false),
        Episode(name: "Beyond Redemption", binged: false),
        Episode(name: "Haunted", binged: false),
        Episode(name: "Lost Souls", binged: false),
        Episode(name: "Brotherhood", binged: false),
        Episode(name: "Legends of Yesterday", binged: false),
        Episode(name: "Dark Waters", binged: false),
        Episode(name: "Blood Debts", binged: false),
        Episode(name: "A.W.O.L.", binged: false),
        Episode(name: "Unchained", binged: false),
        Episode(name: "Sins of the Father", binged: false),
        Episode(name: "Code of Silence", binged: false),
        Episode(name: "Taken", binged: false),
        Episode(name: "Broken Hearts", binged: false),
        Episode(name: "Beacon of Hope", binged: false),
        Episode(name: "Eleven-Fifty-Nine", binged: false),
        Episode(name: "Canary Cry", binged: false),
        Episode(name: "Genesis", binged: false),
        Episode(name: "Monument Point", binged: false),
        Episode(name: "Lost in the Flood", binged: false),
        Episode(name: "Schism", binged: false)
        ],
        [
        Episode(name: "Legacy", binged: false),
        Episode(name: "The Recruits", binged: false),
        Episode(name: "A Matter of Trust", binged: false),
        Episode(name: "Penance", binged: false),
        Episode(name: "Human Target", binged: false),
        Episode(name: "So It Begins", binged: false),
        Episode(name: "Vigilante", binged: false),
        Episode(name: "Invasion!", binged: false),
        Episode(name: "What We Leave Behind", binged: false),
        Episode(name: "Who Are You?", binged: false),
        Episode(name: "Second Chances", binged: false),
        Episode(name: "Bratva", binged: false),
        Episode(name: "Spectre of the Gun", binged: false),
        Episode(name: "The Sin-Eater", binged: false),
        Episode(name: "Fighting Fire with Fire", binged: false),
        Episode(name: "Checkmate", binged: false),
        Episode(name: "Kapiushon", binged: false),
        Episode(name: "Disbanded", binged: false),
        Episode(name: "Dangerous Liaisons", binged: false),
        Episode(name: "Underneath", binged: false),
        Episode(name: "Honor Thy Fathers", binged: false),
        Episode(name: "Missing", binged: false),
        Episode(name: "Lian Yu", binged: false)
        ],
        [
        Episode(name: "Fallout", binged: false),
        Episode(name: "Tribute", binged: false),
        Episode(name: "Next of Kin", binged: false),
        Episode(name: "Reversal", binged: false),
        Episode(name: "Deathstroke Returns", binged: false),
        Episode(name: "Promises Kept", binged: false),
        Episode(name: "Thanksgiving", binged: false),
        Episode(name: "Crisis on Earth-X, Part 2", binged: false),
        Episode(name: "Irreconcilable Differences", binged: false),
        Episode(name: "Divided", binged: false),
        Episode(name: "We Fall", binged: false),
        Episode(name: "All for Nothing", binged: false),
        Episode(name: "The Devil's Greatest Trick", binged: false),
        Episode(name: "Collision Course", binged: false),
        Episode(name: "Doppelganger", binged: false),
        Episode(name: "The Thanatos Guild", binged: false),
        Episode(name: "Brothers in Arms", binged: false),
        Episode(name: "Fundamentals", binged: false),
        Episode(name: "The Dragon", binged: false),
        Episode(name: "Shifting Allegiances", binged: false),
        Episode(name: "Docket No. 11-19-41-73", binged: false),
        Episode(name: "The Ties That Bind", binged: false),
        Episode(name: "Life Sentence", binged: false)
        ],
        [
        Episode(name: "Inmate 4587", binged: false),
        Episode(name: "The Longbow Hunters", binged: false),
        Episode(name: "Crossing Lines", binged: false),
        Episode(name: "Level Two", binged: false),
        Episode(name: "The Demon", binged: false),
        Episode(name: "Due Process", binged: false),
        Episode(name: "The Slabside Redemption", binged: false),
        Episode(name: "Unmasked", binged: false),
        Episode(name: "Elseworlds, Part 2", binged: false),
        Episode(name: "My Name Is Emiko Queen", binged: false),
        Episode(name: "Past Sins", binged: false),
        Episode(name: "Emerald Archer", binged: false),
        Episode(name: "Star City Slayer", binged: false),
        Episode(name: "Brothers & Sisters", binged: false),
        Episode(name: "Training Day", binged: false),
        Episode(name: "Star City 2040", binged: false),
        Episode(name: "Inheritance", binged: false),
        Episode(name: "Lost Canary", binged: false),
        Episode(name: "Spartan", binged: false),
        Episode(name: "Confessions", binged: false),
        Episode(name: "Living Proof", binged: false),
        Episode(name: "You Have Saved This City", binged: false)
        ],
        [
        Episode(name: "Starling City", binged: false),
        Episode(name: "Welcome to Hong Kong", binged: false),
        Episode(name: "Leap of Faith", binged: false),
        Episode(name: "Present Tense", binged: false),
        Episode(name: "Prochnost", binged: false),
        Episode(name: "Reset", binged: false),
        Episode(name: "Purgatory", binged: false),
        Episode(name: "Crisis on Infinite Earths: Part Four", binged: false),
        Episode(name: "Green Arrow and the Canaries", binged: false),
        Episode(name: "Fadeout", binged: false)
        ]]),
        
        Show(name: "Watchmen", favorite: false, episodes: [[
        Episode(name: "It's Summer and We're Running Out of Ice", binged: false),
        Episode(name: "Martial Feats of Comanche Horsemanship", binged: false),
        Episode(name: "She Was Killed by Space Junk", binged: false),
        Episode(name: "If You Don't Like My Story, Write Your Own", binged: false),
        Episode(name: "Little Fear of Lightning", binged: false),
        Episode(name: "This Extraordinary Being", binged: false),
        Episode(name: "An Almost Religious Awe", binged: false),
        Episode(name: "A God Walks into Abar", binged: false),
        Episode(name: "See How They Fly", binged: false)
        ]]),
        
        Show(name: "The Flash", favorite: false, episodes: [[
        Episode(name: "Pilot", binged: false),
        Episode(name: "Fastest Man Alive", binged: false),
        Episode(name: "Things You Can't Outrun", binged: false),
        Episode(name: "Going Rogue", binged: false),
        Episode(name: "Plastique", binged: false),
        Episode(name: "The Flash Is Born", binged: false),
        Episode(name: "Power Outage", binged: false),
        Episode(name: "Flash vs. Arrow", binged: false),
        Episode(name: "The Man in the Yellow Suit", binged: false),
        Episode(name: "Revenge of the Rogues", binged: false),
        Episode(name: "The Sound and the Fury", binged: false),
        Episode(name: "Crazy for You", binged: false),
        Episode(name: "The Nuclear Man", binged: false),
        Episode(name: "Fallout", binged: false),
        Episode(name: "Out of Time", binged: false),
        Episode(name: "Rogue Time", binged: false),
        Episode(name: "Tricksters", binged: false),
        Episode(name: "All Star Team Up", binged: false),
        Episode(name: "Who Is Harrison Wells?", binged: false),
        Episode(name: "The Trap", binged: false),
        Episode(name: "Grodd Lives", binged: false),
        Episode(name: "Rogue Air", binged: false),
        Episode(name: "Fast Enough", binged: false)
        ],
        [
        Episode(name: "The Man Who Saved Central City", binged: false),
        Episode(name: "Flash of Two Worlds", binged: false),
        Episode(name: "Family of Rogues", binged: false),
        Episode(name: "The Fury of Firestorm", binged: false),
        Episode(name: "The Darkness and the Light", binged: false),
        Episode(name: "Enter Zoom", binged: false),
        Episode(name: "Gorilla Warfare", binged: false),
        Episode(name: "Legends of Today", binged: false),
        Episode(name: "Running to Stand Still", binged: false),
        Episode(name: "Potential Energy", binged: false),
        Episode(name: "The Reverse-Flash Returns", binged: false),
        Episode(name: "Fast Lane", binged: false),
        Episode(name: "Welcome to Earth-2", binged: false),
        Episode(name: "Escape from Earth-2", binged: false),
        Episode(name: "King Shark", binged: false),
        Episode(name: "Trajectory", binged: false),
        Episode(name: "Flash Back", binged: false),
        Episode(name: "Versus Zoom", binged: false),
        Episode(name: "Back to Normal", binged: false),
        Episode(name: "Rupture", binged: false),
        Episode(name: "The Runaway Dinosaur", binged: false),
        Episode(name: "Invincible", binged: false),
        Episode(name: "The Race of His Life", binged: false)
        ],
        [
        Episode(name: "Flashpoint", binged: false),
        Episode(name: "Paradox", binged: false),
        Episode(name: "Magenta", binged: false),
        Episode(name: "The New Rogues", binged: false),
        Episode(name: "Monster", binged: false),
        Episode(name: "Shade", binged: false),
        Episode(name: "Killer Frost", binged: false),
        Episode(name: "Invasion!", binged: false),
        Episode(name: "The Present", binged: false),
        Episode(name: "Borrowing Problems from the Future", binged: false),
        Episode(name: "Dead or Alive", binged: false),
        Episode(name: "Untouchable", binged: false),
        Episode(name: "Attack on Gorilla City", binged: false),
        Episode(name: "Attack on Central City", binged: false),
        Episode(name: "The Wrath of Savitar", binged: false),
        Episode(name: "Into the Speed Force", binged: false),
        Episode(name: "Duet", binged: false),
        Episode(name: "Abra Kadabra", binged: false),
        Episode(name: "The Once and Future Flash", binged: false),
        Episode(name: "I Know Who You Are", binged: false),
        Episode(name: "Cause and Effect", binged: false),
        Episode(name: "Infantino Street", binged: false),
        Episode(name: "Finish Line", binged: false)
        ],
        [
        Episode(name: "The Flash Reborn", binged: false),
        Episode(name: "Mixed Signals", binged: false),
        Episode(name: "Luck Be a Lady", binged: false),
        Episode(name: "Elongated Journey Into Night", binged: false),
        Episode(name: "Girls Night Out", binged: false),
        Episode(name: "When Harry Met Harry...", binged: false),
        Episode(name: "Therefore I Am", binged: false),
        Episode(name: "Crisis on Earth-X, Part 3", binged: false),
        Episode(name: "Don't Run", binged: false),
        Episode(name: "The Trial of the Flash", binged: false),
        Episode(name: "The Elongated Knight Rises", binged: false),
        Episode(name: "Honey, I Shrunk Team Flash", binged: false),
        Episode(name: "True Colors", binged: false),
        Episode(name: "Subject 9", binged: false),
        Episode(name: "Enter Flashtime", binged: false),
        Episode(name: "Run, Iris, Run", binged: false),
        Episode(name: "Null and Annoyed", binged: false),
        Episode(name: "Lose Yourself", binged: false),
        Episode(name: "Fury Rogue", binged: false),
        Episode(name: "Therefore She Is", binged: false),
        Episode(name: "Harry and the Harrisons", binged: false),
        Episode(name: "Think Fast", binged: false),
        Episode(name: "We Are the Flash", binged: false)
        ],
        [
        Episode(name: "Nora", binged: false),
        Episode(name: "Blocked", binged: false),
        Episode(name: "The Death of Vibe", binged: false),
        Episode(name: "News Flash", binged: false),
        Episode(name: "All Doll'd Up", binged: false),
        Episode(name: "The Icicle Cometh", binged: false),
        Episode(name: "O Come, All Ye Thankful", binged: false),
        Episode(name: "What's Past Is Prologue", binged: false),
        Episode(name: "Elseworlds, Part 1", binged: false),
        Episode(name: "The Flash & the Furious", binged: false),
        Episode(name: "Seeing Red", binged: false),
        Episode(name: "Memorabilia", binged: false),
        Episode(name: "Goldfaced", binged: false),
        Episode(name: "Cause and XS", binged: false),
        Episode(name: "King Shark vs. Gorilla Grodd", binged: false),
        Episode(name: "Failure Is an Orphan", binged: false),
        Episode(name: "Time Bomb", binged: false),
        Episode(name: "Godspeed", binged: false),
        Episode(name: "Snow Pack", binged: false),
        Episode(name: "Gone Rogue", binged: false),
        Episode(name: "The Girl with the Red Lightning", binged: false),
        Episode(name: "Legacy", binged: false)
        ],
        [
        Episode(name: "Into the Void", binged: false),
        Episode(name: "A Flash of the Lightning", binged: false),
        Episode(name: "Dead Man Running", binged: false),
        Episode(name: "There Will Be Blood", binged: false),
        Episode(name: "Kiss Kiss Breach Breach", binged: false),
        Episode(name: "License to Elongate", binged: false),
        Episode(name: "The Last Temptation of Barry Allen, Pt. 1", binged: false),
        Episode(name: "The Last Temptation of Barry Allen, Pt. 2", binged: false),
        Episode(name: "Crisis on Infinite Earths: Part Three", binged: false),
        Episode(name: "Marathon", binged: false)
        ]]),
        
        //daredevil
        Show(name: "DareDevil", favorite: false, episodes: [[
        Episode(name: "Into the Ring", binged: false),
        Episode(name: "Cut Man", binged: false),
        Episode(name: "Rabbit in a Snowstorm", binged: false),
        Episode(name: "In the Blood", binged: false),
        Episode(name: "World on Fire", binged: false),
        Episode(name: "Condemned", binged: false),
        Episode(name: "Stick", binged: false),
        Episode(name: "Shadows in the Glass", binged: false),
        Episode(name: "Speak of the Devil", binged: false),
        Episode(name: "Nelson v. Murdock", binged: false),
        Episode(name: "The Path of the Righteous", binged: false),
        Episode(name: "The Ones We Leave Behind", binged: false),
        Episode(name: "Daredevil", binged: false)
        ],
        [
        Episode(name: "Bang", binged: false),
        Episode(name: "Dogs to a Gunfight", binged: false),
        Episode(name: "New York's Finest", binged: false),
        Episode(name: "Penny and Dime", binged: false),
        Episode(name: "Kinbaku", binged: false),
        Episode(name: "Regrets Only", binged: false),
        Episode(name: "Semper Fidelis", binged: false),
        Episode(name: "Guilty as Sin", binged: false),
        Episode(name: "Seven Minutes in Heaven", binged: false),
        Episode(name: "The Man in the Box", binged: false),
        Episode(name: ".380", binged: false),
        Episode(name: "The Dark at the End of the Tunnel", binged: false),
        Episode(name: "A Cold Day in Hell's Kitchen", binged: false)
        ],
        [
        Episode(name: "Resurrection", binged: false),
        Episode(name: "Please", binged: false),
        Episode(name: "No Good Deed", binged: false),
        Episode(name: "Blindsided", binged: false),
        Episode(name: "The Perfect Game", binged: false),
        Episode(name: "The Devil You Know", binged: false),
        Episode(name: "Aftermath", binged: false),
        Episode(name: "Upstairs/Downstairs", binged: false),
        Episode(name: "Revelations", binged: false),
        Episode(name: "Karen", binged: false),
        Episode(name: "Reunion", binged: false),
        Episode(name: "One Last Shot", binged: false),
        Episode(name: "A New Napkin", binged: false),
        ]]),
        
        Show(name: "The Adventures of Superman", favorite: false, episodes: [[
        Episode(name: "Superman on Earth", binged: false),
        Episode(name: "The Haunted Lighthouse", binged: false),
        Episode(name: "The Case of the Talkative Dummy", binged: false),
        Episode(name: "Mystery of the Broken Statues", binged: false),
        Episode(name: "The Monkey Mystery", binged: false),
        Episode(name: "Night of Terror", binged: false),
        Episode(name: "The Birthday Letter", binged: false),
        Episode(name: "The Mind Machine", binged: false),
        Episode(name: "Rescue", binged: false),
        Episode(name: "The Secret of Superman", binged: false),
        Episode(name: "No Holds Barred", binged: false),
        Episode(name: "The Deserted Village", binged: false),
        Episode(name: "The Stolen Costume", binged: false),
        Episode(name: "Mystery in Wax", binged: false),
        Episode(name: "Treasure of the Incas", binged: false),
        Episode(name: "Double Trouble", binged: false),
        Episode(name: "The Runaway Robot", binged: false),
        Episode(name: "Drums of Death", binged: false),
        Episode(name: "The Evil Three", binged: false),
        Episode(name: "Riddle of the Chinese Jade", binged: false),
        Episode(name: "The Human Bomb", binged: false),
        Episode(name: "Czar of the Underworld", binged: false),
        Episode(name: "Ghost Wolf", binged: false),
        Episode(name: "Crime Wave", binged: false),
        Episode(name: "The Unknown People – Part 1", binged: false),
        Episode(name: "The Unknown People – Part 2", binged: false)
        ],
        [
        Episode(name: "Five Minutes to Doom", binged: false),
        Episode(name: "The Big Squeeze", binged: false),
        Episode(name: "The Man Who Could Read Minds", binged: false),
        Episode(name: "Jet Ace", binged: false),
        Episode(name: "Shot in the Dark", binged: false),
        Episode(name: "The Defeat of Superman", binged: false),
        Episode(name: "Superman in Exile", binged: false),
        Episode(name: "A Ghost for Scotland Yard", binged: false),
        Episode(name: "The Dog Who Knew Superman", binged: false),
        Episode(name: "The Face and the Voice", binged: false),
        Episode(name: "The Man in the Lead Mask", binged: false),
        Episode(name: "Panic in the Sky", binged: false),
        Episode(name: "The Machine That Could Plot Crimes", binged: false),
        Episode(name: "Jungle Devil", binged: false),
        Episode(name: "My Friend Superman", binged: false),
        Episode(name: "The Clown Who Cried", binged: false),
        Episode(name: "The Boy Who Hated Superman", binged: false),
        Episode(name: "Semi-Private Eye", binged: false),
        Episode(name: "Perry White's Scoop", binged: false),
        Episode(name: "Beware the Wrecker", binged: false),
        Episode(name: "The Golden Vulture", binged: false),
        Episode(name: "Jimmy Olsen, Boy Editor", binged: false),
        Episode(name: "Lady in Black", binged: false),
        Episode(name: "Star of Fate", binged: false),
        Episode(name: "The Whistling Bird", binged: false),
        Episode(name: "Around the World with Superman", binged: false)
        ],
        [
        Episode(name: "Through the Time Barrier", binged: false),
        Episode(name: "The Talking Clue", binged: false),
        Episode(name: "The Lucky Cat", binged: false),
        Episode(name: "Superman Week", binged: false),
        Episode(name: "Great Caesar's Ghost", binged: false),
        Episode(name: "Test of a Warrior", binged: false),
        Episode(name: "Olsen's Millions", binged: false),
        Episode(name: "Clark Kent, Outlaw", binged: false),
        Episode(name: "The Magic Necklace", binged: false),
        Episode(name: "The Bully of Dry Gulch", binged: false),
        Episode(name: "Flight to the North", binged: false),
        Episode(name: "The Seven Souvenirs", binged: false),
        Episode(name: "King for a Day", binged: false)
        ],
        [
        Episode(name: "Joey", binged: false),
        Episode(name: "The Unlucky Number", binged: false),
        Episode(name: "The Big Freeze", binged: false),
        Episode(name: "Peril by Sea", binged: false),
        Episode(name: "Topsy Turvy", binged: false),
        Episode(name: "Jimmy the Kid", binged: false),
        Episode(name: "The Girl Who Hired Superman", binged: false),
        Episode(name: "The Wedding of Superman", binged: false),
        Episode(name: "Dagger Island", binged: false),
        Episode(name: "Blackmail", binged: false),
        Episode(name: "The Deadly Rock", binged: false),
        Episode(name: "The Phantom Ring", binged: false),
        Episode(name: "The Jolly Roger", binged: false)
        ],
        [
        Episode(name: "Peril in Paris", binged: false),
        Episode(name: "Tin Hero", binged: false),
        Episode(name: "The Town That Wasn't", binged: false),
        Episode(name: "The Tomb of Zaharan", binged: false),
        Episode(name: "The Man Who Made Dreams Come True", binged: false),
        Episode(name: "Disappearing Lois", binged: false),
        Episode(name: "Money to Burn", binged: false),
        Episode(name: "Close Shave", binged: false),
        Episode(name: "The Phony Alibi", binged: false),
        Episode(name: "The Prince Albert Coat", binged: false),
        Episode(name: "The Stolen Elephant", binged: false),
        Episode(name: "Mr. Zero", binged: false),
        Episode(name: "Whatever Goes Up", binged: false)
        ],
        [
        Episode(name: "The Last Knight", binged: false),
        Episode(name: "The Magic Secret", binged: false),
        Episode(name: "Divide and Conquer", binged: false),
        Episode(name: "The Mysterious Cube", binged: false),
        Episode(name: "The Atomic Captive", binged: false),
        Episode(name: "The Superman Silver Mine", binged: false),
        Episode(name: "The Big Forget", binged: false),
        Episode(name: "The Gentle Monster", binged: false),
        Episode(name: "Superman's Wife", binged: false),
        Episode(name: "Three in One", binged: false),
        Episode(name: "The Brainy Burro", binged: false),
        Episode(name: "The Perils of Superman", binged: false),
        Episode(name: "All That Glitters", binged: false)
        ],
        ]),
        Show(name: "Batman", favorite: false, episodes: [[
        Episode(name: "Hi Diddle Riddle", binged: false),
        Episode(name: "Smack in the Middle", binged: false),
        Episode(name: "Fine Feathered Finks ", binged: false),
        Episode(name: "The Penguin's a Jinx", binged: false),
        Episode(name: "The Joker Is Wild", binged: false),
        Episode(name: "Batman Is Riled", binged: false),
        Episode(name: "Instant Freeze", binged: false),
        Episode(name: "Rats Like Cheese", binged: false),
        Episode(name: "Zelda the Great", binged: false),
        Episode(name: "A Death Worse Than Fate", binged: false),
        Episode(name: "A Riddle a Day Keeps the Riddler Away", binged: false),
        Episode(name: "When the Rat's Away, the Mice Will Play", binged: false),
        Episode(name: "The Thirteenth Hat", binged: false),
        Episode(name: "Batman Stands Pat", binged: false),
        Episode(name: "The Joker Goes to School", binged: false),
        Episode(name: "He Meets His Match, the Grisly Ghoul", binged: false),
        Episode(name: "True or False-Face", binged: false),
        Episode(name: "Holy Rat Race", binged: false),
        Episode(name: "The Purr-fect Crime", binged: false),
        Episode(name: "Better Luck Next Time", binged: false),
        Episode(name: "The Penguin Goes Straight", binged: false),
        Episode(name: "Not Yet, He Ain't", binged: false),
        Episode(name: "The Ring of Wax", binged: false),
        Episode(name: "Give 'Em the Axe", binged: false),
        Episode(name: "The Joker Trumps an Ace", binged: false),
        Episode(name: "Batman Sets the Pace", binged: false),
        Episode(name: "The Curse of Tut", binged: false),
        Episode(name: "The Pharaoh's in a Rut", binged: false),
        Episode(name: "The Bookworm Turns", binged: false),
        Episode(name: "While Gotham City Burns", binged: false),
        Episode(name: "Death in Slow Motion", binged: false),
        Episode(name: "The Riddler's False Notion", binged: false),
        Episode(name: "Fine Finny Fiends", binged: false),
        Episode(name: "Batman Makes the Scenes", binged: false)
        ],
        [
        Episode(name: "Shoot a Crooked Arrow", binged: false),
        Episode(name: "Walk the Straight and Narrow", binged: false),
        Episode(name: "Hot Off the Griddle", binged: false),
        Episode(name: "The Cat and the Fiddle", binged: false),
        Episode(name: "The Minstrel's Shakedown", binged: false),
        Episode(name: "Barbecued Batman?", binged: false),
        Episode(name: "The Spell of Tut", binged: false),
        Episode(name: "Tut's Case is Shut", binged: false),
        Episode(name: "The Greatest Mother of Them All", binged: false),
        Episode(name: "Ma Parker", binged: false),
        Episode(name: "The Clock King's Crazy Crimes", binged: false),
        Episode(name: "The Clock King Gets Crowned", binged: false),
        Episode(name: "An Egg Grows in Gotham", binged: false),
        Episode(name: "The Yegg Foes in Gotham", binged: false),
        Episode(name: "The Devil's Fingers", binged: false),
        Episode(name: "The Dead Ringers", binged: false),
        Episode(name: "Hizzonner the Penguin", binged: false),
        Episode(name: "Dizzoner the Penguin", binged: false),
        Episode(name: "Green Ice", binged: false),
        Episode(name: "Deep Freeze", binged: false),
        Episode(name: "The Impractical Joker", binged: false),
        Episode(name: "The Joker's Provokers", binged: false),
        Episode(name: "Marsha, Queen of Diamonds", binged: false),
        Episode(name: "Marsha's Scheme of Diamonds", binged: false),
        Episode(name: "Come Back, Shame", binged: false),
        Episode(name: "It's How You Play the Game", binged: false),
        Episode(name: "The Penguin's Nest", binged: false),
        Episode(name: "The Bird's Last Jest", binged: false),
        Episode(name: "The Cat's Meow", binged: false),
        Episode(name: "The Bat's Kow Tow", binged: false),
        Episode(name: "The Puzzles Are Coming", binged: false),
        Episode(name: "The Duo is Slumming", binged: false),
        Episode(name: "The Sandman Cometh", binged: false),
        Episode(name: "The Catwoman Goeth", binged: false),
        Episode(name: "The Contaminated Cowl", binged: false),
        Episode(name: "The Mad Hatter Runs Afoul", binged: false),
        Episode(name: "The Zodiac Crimes", binged: false),
        Episode(name: "The Joker's Hard Times", binged: false),
        Episode(name: "The Penguin Declines", binged: false),
        Episode(name: "That Darn Catwoman", binged: false),
        Episode(name: "Scat! Darn Catwoman", binged: false),
        Episode(name: "Penguin Is a Girl's Best Friend", binged: false),
        Episode(name: "Penguin Sets a Trend", binged: false),
        Episode(name: "Penguin's Disastrous End", binged: false),
        Episode(name: "Batman's Anniversary", binged: false),
        Episode(name: "A Riddling Controversy", binged: false),
        Episode(name: "The Joker's Last Laugh", binged: false),
        Episode(name: "The Joker's Epitaph", binged: false),
        Episode(name: "Catwoman Goes to College", binged: false),
        Episode(name: "Batman Displays His Knowledge", binged: false),
        Episode(name: "A Piece of the Action", binged: false),
        Episode(name: "Batman's Satisfaction[nb 1]", binged: false),
        Episode(name: "King Tut's Coup", binged: false),
        Episode(name: "Batman's Waterloo", binged: false),
        Episode(name: "Black Widow Strikes Again", binged: false),
        Episode(name: "Caught in the Spider's Den", binged: false),
        Episode(name: "Pop Goes the Joker", binged: false),
        Episode(name: "Flop Goes the Joker", binged: false),
        Episode(name: "Ice Spy", binged: false),
        Episode(name: "The Duo Defy", binged: false)
        ],
        [
        Episode(name: "Enter Batgirl, Exit Penguin", binged: false),
        Episode(name: "Ring Around the Riddler", binged: false),
        Episode(name: "The Wail of the Siren", binged: false),
        Episode(name: "The Sport of Penguins", binged: false),
        Episode(name: "A Horse of Another Color", binged: false),
        Episode(name: "The Unkindest Tut of All", binged: false),
        Episode(name: "Louie the Lilac", binged: false),
        Episode(name: "The Ogg and I", binged: false),
        Episode(name: "How to Hatch a Dinosaur", binged: false),
        Episode(name: "Surf's Up! Joker's Under!", binged: false),
        Episode(name: "The Londinium Larcenies", binged: false),
        Episode(name: "The Foggiest Notion", binged: false),
        Episode(name: "The Bloody Tower", binged: false),
        Episode(name: "Catwoman's Dressed to Kill", binged: false),
        Episode(name: "The Ogg Couple", binged: false),
        Episode(name: "The Funny Feline Felonies", binged: false),
        Episode(name: "The Joke's on Catwoman", binged: false),
        Episode(name: "Louie's Lethal Lilac Time", binged: false),
        Episode(name: "Nora Clavicle and the", binged: false),
        Episode(name: "Penguin's Clean Sweep", binged: false),
        Episode(name: "The Great Escape", binged: false),
        Episode(name: "The Great Train Robbery", binged: false),
        Episode(name: "I'll Be a Mummy's Uncle", binged: false),
        Episode(name: "The Joker's Flying Saucer", binged: false),
        Episode(name: "The Entrancing Dr. Cassandra", binged: false),
        Episode(name: "Minerva, Mayhem and Millionaires", binged: false)
        ]]),
        Show(name: "Birds of Prey", favorite: false, episodes: [[
        Episode(name: "Pilot", binged: false),
        Episode(name: "Slick", binged: false),
        Episode(name: "Prey for the Hunter", binged: false),
        Episode(name: "Three Birds and a Baby", binged: false),
        Episode(name: "Sins of the Mother", binged: false),
        Episode(name: "Primal Scream", binged: false),
        Episode(name: "Split", binged: false),
        Episode(name: "Lady Shiva", binged: false),
        Episode(name: "Nature of the Beast", binged: false),
        Episode(name: "Gladiatrix", binged: false),
        Episode(name: "Reunion", binged: false),
        Episode(name: "Feat of Clay", binged: false),
        Episode(name: "Devil's Eyes", binged: false)
        ]]),
        Show(name: "Constantine", favorite: false, episodes: [[
        Episode(name: "Non Est Asylum", binged: false),
        Episode(name: "The Darkness Beneath", binged: false),
        Episode(name: "The Devil's Vinyl", binged: false),
        Episode(name: "A Feast of Friends", binged: false),
        Episode(name: "Danse Vaudou", binged: false),
        Episode(name: "Rage of Caliban", binged: false),
        Episode(name: "Blessed Are the Damned", binged: false),
        Episode(name: "The Saint of Last Resorts", binged: false),
        Episode(name: "The Saint of Last Resorts: Part 2", binged: false),
        Episode(name: "Quid Pro Quo", binged: false),
        Episode(name: "A Whole World Out There", binged: false),
        Episode(name: "Angels and Ministers of Grace", binged: false),
        Episode(name: "Waiting for the Man", binged: false)
        ]]),
        Show(name: "Powerless", favorite: false, episodes: [[
        Episode(name:"Wayne or Lose", binged: false),
        Episode(name:"Wayne Dream Team", binged: false),
        Episode(name:"Sinking Day", binged: false),
        Episode(name:"Emily Dates a Henchman", binged: false),
        Episode(name:"Cold Season", binged: false),
        Episode(name:"I'ma Friend You", binged: false),
        Episode(name:"Van v Emily: Dawn of Justice", binged: false),
        Episode(name:"Green Furious", binged: false),
        Episode(name:"Emergency Punch-Up", binged: false),
        Episode(name:"No Consequence Day", binged: false),
        Episode(name:"Van of the Year", binged: false),
        Episode(name:"Win, Luthor, Draw", binged: false)
        ]]),
        Show(name: "Swamp Thing", favorite: false, episodes: [[
        Episode(name:"Pilot", binged: false),
        Episode(name:"Worlds Apart", binged: false),
        Episode(name:"He Speaks", binged: false),
        Episode(name:"Darkness on the Edge of Town", binged: false),
        Episode(name:"Drive All Night", binged: false),
        Episode(name:"The Price You Pay", binged: false),
        Episode(name:"Brilliant Disguise", binged: false),
        Episode(name:"Long Walk Home", binged: false),
        Episode(name:"The Anatomy Lesson", binged: false),
        Episode(name:"Loose Ends", binged: false)
        ]]),
        Show(name: "Doom Patrol", favorite: false, episodes: [[
        Episode(name:"Pilot", binged: false),
        Episode(name:"Donkey Patrol", binged: false),
        Episode(name:"Puppet Patrol", binged: false),
        Episode(name:"Cult Patrol", binged: false),
        Episode(name:"Paw Patrol", binged: false),
        Episode(name:"Doom Patrol Patrol", binged: false),
        Episode(name:"Therapy Patrol", binged: false),
        Episode(name:"Danny Patrol", binged: false),
        Episode(name:"Jane Patrol", binged: false),
        Episode(name:"Hair Patrol", binged: false),
        Episode(name:"Frances Patrol", binged: false),
        Episode(name:"Cyborg Patrol", binged: false),
        Episode(name:"Flex Patrol", binged: false),
        Episode(name:"Penultimate Patrol", binged: false),
        Episode(name:"Ezekiel Patrol", binged: false)
        ]]),
        Show(name: "Pennyworth", favorite: false, episodes: [[
        Episode(name:"Pilot", binged: false),
        Episode(name:"The Landlord's Daughter", binged: false),
        Episode(name:"Martha Kane", binged: false),
        Episode(name:"Lady Penelope", binged: false),
        Episode(name:"Shirley Bassey", binged: false),
        Episode(name:"Cilla Black", binged: false),
        Episode(name:"Julie Christie", binged: false),
        Episode(name:"Sandie Shaw", binged: false),
        Episode(name:"Alma Cogan", binged: false),
        Episode(name:"Marianne Faithfull", binged: false)
        ]]),
        Show(name: "Batwoman", favorite: false, episodes: [[
        Episode(name:"Pilot", binged: false),
        Episode(name:"The Rabbit Hole", binged: false),
        Episode(name:"Down Down Down", binged: false),
        Episode(name:"Who Are You?", binged: false),
        Episode(name:"Mine Is a Long and a Sad Tale", binged: false),
        Episode(name:"I'll Be Judge, I'll Be Jury", binged: false),
        Episode(name:"Tell Me the Truth", binged: false),
        Episode(name:"A Mad Tea-Party", binged: false),
        Episode(name:"Crisis on Infinite Earths: Part Two", binged: false),
        Episode(name:"How Queer Everything Is Today![25]", binged: false),
        Episode(name:"An Un-Birthday Present[26]", binged: false)
        ]]),
        Show(name: "Krypton", favorite: false, episodes: [[
        Episode(name:"Pilot", binged: false),
        Episode(name:"House of El", binged: false),
        Episode(name:"The Rankless Initiative", binged: false),
        Episode(name:"The Word of Rao", binged: false),
        Episode(name:"House of Zod", binged: false),
        Episode(name:"Civil Wars", binged: false),
        Episode(name:"Transformation", binged: false),
        Episode(name:"Savage Night", binged: false),
        Episode(name:"Hope", binged: false),
        Episode(name:"The Phantom Zone", binged: false)
        ],
        [
        Episode(name:"Light-Years From Home", binged: false),
        Episode(name:"Ghost in the Fire", binged: false),
        Episode(name:"Will to Power", binged: false),
        Episode(name:"Danger Close", binged: false),
        Episode(name:"A Better Yesterday", binged: false),
        Episode(name:"In Zod We Trust", binged: false),
        Episode(name:"Zods and Monsters", binged: false),
        Episode(name:"Mercy", binged: false),
        Episode(name:"Blood Moon", binged: false),
        Episode(name:"The Alpha and the Omega", binged: false)
        ]]),
        Show(name: "Gotham", favorite: false, episodes: [
        [
        Episode(name:"Pilot", binged: false),
        Episode(name:"Worlds Apart", binged: false),
        Episode(name:"He Speaks", binged: false),
        Episode(name:"Darkness on the Edge of Town", binged: false),
        Episode(name:"Drive All Night", binged: false),
        Episode(name:"The Price You Pay", binged: false),
        Episode(name:"Brilliant Disguise", binged: false),
        Episode(name:"Long Walk Home", binged: false),
        Episode(name:"The Anatomy Lesson", binged: false),
        Episode(name:"Loose Ends", binged: false)
        ],
        [
        Episode(name:"Damned If You Do...", binged: false),
        Episode(name:"Knock, Knock", binged: false),
        Episode(name:"The Last Laugh", binged: false),
        Episode(name:"Strike Force", binged: false),
        Episode(name:"Scarification", binged: false),
        Episode(name:"By Fire", binged: false),
        Episode(name:"Mommy's Little Monster", binged: false),
        Episode(name:"Tonight's the Night", binged: false),
        Episode(name:"A Bitter Pill to Swallow", binged: false),
        Episode(name:"The Son of Gotham", binged: false),
        Episode(name:"Worse Than a Crime", binged: false),
        Episode(name:"Mr. Freeze", binged: false),
        Episode(name:"A Dead Man Feels No Cold", binged: false),
        Episode(name:"This Ball of Mud and Meanness", binged: false),
        Episode(name:"Mad Grey Dawn", binged: false),
        Episode(name:"Prisoners", binged: false),
        Episode(name:"Into the Woods", binged: false),
        Episode(name:"Pinewood", binged: false),
        Episode(name:"Azrael", binged: false),
        Episode(name:"Unleashed", binged: false),
        Episode(name:"A Legion of Horribles", binged: false),
        Episode(name:"Transference", binged: false)
        ],
        [
        Episode(name:"Better to Reign in Hell...", binged: false),
        Episode(name:"Burn the Witch", binged: false),
        Episode(name:"Look into My Eyes", binged: false),
        Episode(name:"New Day Rising", binged: false),
        Episode(name:"Anything for You", binged: false),
        Episode(name:"Follow the White Rabbit", binged: false),
        Episode(name:"Red Queen", binged: false),
        Episode(name:"Blood Rush", binged: false),
        Episode(name:"The Executioner", binged: false),
        Episode(name:"Time Bomb", binged: false),
        Episode(name:"Beware the Green-Eyed Monster", binged: false),
        Episode(name:"Ghosts", binged: false),
        Episode(name:"Smile Like You Mean It", binged: false),
        Episode(name:"The Gentle Art of Making Enemies", binged: false),
        Episode(name:"How the Riddler Got His Name", binged: false),
        Episode(name:"These Delicate and Dark Obsessions", binged: false),
        Episode(name:"The Primal Riddle", binged: false),
        Episode(name:"Light the Wick", binged: false),
        Episode(name:"All Will Be Judged", binged: false),
        Episode(name:"Pretty Hate Machine", binged: false),
        Episode(name:"Destiny Calling", binged: false),
        Episode(name:"Heavydirtysoul", binged: false)
        ],
        [
        Episode(name:"Pax Penguina", binged: false),
        Episode(name:"The Fear Reaper", binged: false),
        Episode(name:"They Who Hide Behind Masks", binged: false),
        Episode(name:"The Demon's Head", binged: false),
        Episode(name:"The Blade's Path", binged: false),
        Episode(name:"Hog Day Afternoon", binged: false),
        Episode(name:"A Day in the Narrows", binged: false),
        Episode(name:"Stop Hitting Yourself", binged: false),
        Episode(name:"Let Them Eat Pie", binged: false),
        Episode(name:"Things That Go Boom", binged: false),
        Episode(name:"Queen Takes Knight", binged: false),
        Episode(name:"Pieces of a Broken Mirror", binged: false),
        Episode(name:"A Beautiful Darkness", binged: false),
        Episode(name:"Reunion", binged: false),
        Episode(name:"The Sinking Ship The Grand Applause", binged: false),
        Episode(name:"One of My Three Soups", binged: false),
        Episode(name:"Mandatory Brunch Meeting", binged: false),
        Episode(name:"That's Entertainment", binged: false),
        Episode(name:"To Our Deaths and Beyond", binged: false),
        Episode(name:"That Old Corpse", binged: false),
        Episode(name:"One Bad Day", binged: false),
        Episode(name:"No Man's Land", binged: false)
        ],
        [
        Episode(name:"Year Zero", binged: false),
        Episode(name:"Trespassers", binged: false),
        Episode(name:"Penguin, Our Hero", binged: false),
        Episode(name:"Ruin", binged: false),
        Episode(name:"Pena Dura", binged: false),
        Episode(name:"13 Stitches", binged: false),
        Episode(name:"Ace Chemicals", binged: false),
        Episode(name:"Nothing's Shocking", binged: false),
        Episode(name:"The Trial of Jim Gordon", binged: false),
        Episode(name:"I Am Bane", binged: false),
        Episode(name:"They Did What?", binged: false),
        Episode(name:"The Beginning...", binged: false)
        ]]),
        Show(name: "Agents of Shield", favorite: false, episodes: [
        [
        Episode(name:"Pilot", binged: false),
        Episode(name:"0-8-4", binged: false),
        Episode(name:"The Asset", binged: false),
        Episode(name:"Eye Spy", binged: false),
        Episode(name:"Girl in the Flower Dress", binged: false),
        Episode(name:"FZZT", binged: false),
        Episode(name:"The Hub", binged: false),
        Episode(name:"The Well", binged: false),
        Episode(name:"Repairs", binged: false),
        Episode(name:"The Bridge", binged: false),
        Episode(name:"The Magical Place", binged: false),
        Episode(name:"Seeds", binged: false),
        Episode(name:"T.R.A.C.K.S.", binged: false),
        Episode(name:"T.A.H.I.T.I.", binged: false),
        Episode(name:"Yes Men", binged: false),
        Episode(name:"End of the Beginning", binged: false),
        Episode(name:"Turn, Turn, Turn", binged: false),
        Episode(name:"Providence", binged: false),
        Episode(name:"The Only Light in the Darkness", binged: false),
        Episode(name:"Nothing Personal", binged: false),
        Episode(name:"Ragtag", binged: false),
        Episode(name:"Beginning of the End", binged: false)
        ],
        [
        Episode(name:"Shadows", binged: false),
        Episode(name:"Heavy Is the Head", binged: false),
        Episode(name:"Making Friends and Influencing People", binged: false),
        Episode(name:"Face My Enemy", binged: false),
        Episode(name:"A Hen in the Wolf House", binged: false),
        Episode(name:"A Fractured House", binged: false),
        Episode(name:"The Writing on the Wall", binged: false),
        Episode(name:"The Things We Bury", binged: false),
        Episode(name:"...Ye Who Enter Here", binged: false),
        Episode(name:"What They Become", binged: false),
        Episode(name:"Aftershocks", binged: false),
        Episode(name:"Who You Really Are", binged: false),
        Episode(name:"One of Us", binged: false),
        Episode(name:"Love in the Time of Hydra", binged: false),
        Episode(name:"One Door Closes", binged: false),
        Episode(name:"Afterlife", binged: false),
        Episode(name:"Melinda", binged: false),
        Episode(name:"The Frenemy of My Enemy", binged: false),
        Episode(name:"The Dirty Half Dozen", binged: false),
        Episode(name:"Scars", binged: false),
        Episode(name:"S.O.S.", binged: false),
        Episode(name:"Laws of Nature", binged: false),
        Episode(name:"Purpose in the Machine", binged: false),
        Episode(name:"A Wanted (Inhu)man", binged: false),
        Episode(name:"Devils You Know", binged: false),
        Episode(name:"4,722 Hours", binged: false),
        Episode(name:"Among Us Hide...", binged: false),
        Episode(name:"Chaos Theory", binged: false),
        Episode(name:"Many Heads, One Tale", binged: false),
        Episode(name:"Closure", binged: false),
        Episode(name:"Maveth", binged: false),
        Episode(name:"Bouncing Back", binged: false),
        Episode(name:"The Inside Man", binged: false),
        Episode(name:"Parting Shot", binged: false),
        Episode(name:"Watchdogs", binged: false),
        Episode(name:"Spacetime", binged: false),
        Episode(name:"Paradise Lost", binged: false),
        Episode(name:"The Team", binged: false),
        Episode(name:"The Singularity", binged: false),
        Episode(name:"Failed Experiments", binged: false),
        Episode(name:"Emancipation", binged: false),
        Episode(name:"Absolution", binged: false),
        Episode(name:"Ascension", binged: false)
        ],
        [
        Episode(name:"The Ghost", binged: false),
        Episode(name:"Meet the New Boss", binged: false),
        Episode(name:"Uprising", binged: false),
        Episode(name:"Let Me Stand Next to Your Fire", binged: false),
        Episode(name:"Lockup", binged: false),
        Episode(name:"The Good Samaritan", binged: false),
        Episode(name:"Deals with Our Devils", binged: false),
        Episode(name:"The Laws of Inferno Dynamics", binged: false),
        Episode(name:"Broken Promises", binged: false),
        Episode(name:"The Patriot", binged: false),
        Episode(name:"Wake Up", binged: false),
        Episode(name:"Hot Potato Soup", binged: false),
        Episode(name:"BOOM", binged: false),
        Episode(name:"The Man Behind the Shield", binged: false),
        Episode(name:"Self Control", binged: false),
        Episode(name:"What If...", binged: false),
        Episode(name:"Identity and Change", binged: false),
        Episode(name:"No Regrets", binged: false),
        Episode(name:"All the Madame's Men", binged: false),
        Episode(name:"Farewell, Cruel World!", binged: false),
        Episode(name:"The Return", binged: false),
        Episode(name:"World's End", binged: false)
        ],
        [
        Episode(name:"A Life Spent", binged: false),
        Episode(name:"A Life Earned", binged: false),
        Episode(name:"Rewind", binged: false),
        Episode(name:"Fun & Games", binged: false),
        Episode(name:"Together or Not at All", binged: false),
        Episode(name:"The Last Day", binged: false),
        Episode(name:"Best Laid Plans", binged: false),
        Episode(name:"Past Life", binged: false),
        Episode(name:"All the Comforts of Home", binged: false),
        Episode(name:"The Real Deal", binged: false),
        Episode(name:"Principia", binged: false),
        Episode(name:"The Devil Complex", binged: false),
        Episode(name:"Rise and Shine", binged: false),
        Episode(name:"Inside Voices", binged: false),
        Episode(name:"The Honeymoon", binged: false),
        Episode(name:"All Roads Lead...", binged: false),
        Episode(name:"Option Two", binged: false),
        Episode(name:"The One Who Will Save Us All", binged: false),
        Episode(name:"The Force of Gravity", binged: false),
        Episode(name:"The End", binged: false)
        ],
        [
        Episode(name:"Missing Pieces", binged: false),
        Episode(name:"Window of Opportunity", binged: false),
        Episode(name:"Fear and Loathing on the Planet of Kitson", binged: false),
        Episode(name:"Code Yellow", binged: false),
        Episode(name:"The Other Thing", binged: false),
        Episode(name:"Inescapable", binged: false),
        Episode(name:"Toldja", binged: false),
        Episode(name:"Collision Course (Part I)", binged: false),
        Episode(name:"Collision Course (Part II)", binged: false),
        Episode(name:"Leap", binged: false),
        Episode(name:"From the Ashes", binged: false),
        Episode(name:"The Sign", binged: false),
        Episode(name:"New Life", binged: false)
        ]]),
        Show(name: "Iron Fist", favorite: false, episodes: [
        [
        Episode(name:"Snow Gives Way", binged: false),
        Episode(name:"Shadow Hawk Takes Flight", binged: false),
        Episode(name:"Rolling Thunder Cannon Punch", binged: false),
        Episode(name:"Eight Diagram Dragon Palm", binged: false),
        Episode(name:"Under Leaf Pluck Lotus", binged: false),
        Episode(name:"Immortal Emerges from Cave", binged: false),
        Episode(name:"Felling Tree with Roots", binged: false),
        Episode(name:"The Blessing of Many Fractures", binged: false),
        Episode(name:"The Mistress of All Agonies", binged: false),
        Episode(name:"Black Tiger Steals Heart", binged: false),
        Episode(name:"Lead Horse Back to Stable", binged: false),
        Episode(name:"Bar the Big Boss", binged: false),
        Episode(name:"Dragon Plays with Fire", binged: false)
        ],
        [
        Episode(name:"The Fury of Iron Fist", binged: false),
        Episode(name:"The City's Not for Burning", binged: false),
        Episode(name:"This Deadly Secret", binged: false),
        Episode(name:"Target: Iron Fist", binged: false),
        Episode(name:"Heart of the Dragon", binged: false),
        Episode(name:"The Dragon Dies at Dawn", binged: false),
        Episode(name:"Morning of the Mindstorm", binged: false),
        Episode(name:"Citadel on the Edge of Vengeance", binged: false),
        Episode(name:"War Without End", binged: false),
        Episode(name:"A Duel of Iron", binged: false)
        ]]),
        Show(name: "Jessica Jones", favorite: false, episodes: [
        [
        Episode(name:"AKA Ladies Night", binged: false),
        Episode(name:"AKA Crush Syndrome", binged: false),
        Episode(name:"AKA It's Called Whiskey", binged: false),
        Episode(name:"AKA 99 Friends", binged: false),
        Episode(name:"AKA The Sandwich Saved Me", binged: false),
        Episode(name:"AKA You're a Winner!", binged: false),
        Episode(name:"AKA Top Shelf Perverts", binged: false),
        Episode(name:"AKA WWJD?", binged: false),
        Episode(name:"AKA Sin Bin", binged: false),
        Episode(name:"AKA 1,000 Cuts", binged: false),
        Episode(name:"AKA I've Got the Blues", binged: false),
        Episode(name:"AKA Take a Bloody Number", binged: false),
        Episode(name:"AKA Smile", binged: false)
        ],
        [
        Episode(name:"AKA Start at the Beginning", binged: false),
        Episode(name:"AKA Freak Accident", binged: false),
        Episode(name:"AKA Sole Survivor", binged: false),
        Episode(name:"AKA God Help the Hobo", binged: false),
        Episode(name:"AKA The Octopus", binged: false),
        Episode(name:"AKA Facetime", binged: false),
        Episode(name:"AKA I Want Your Cray Cray", binged: false),
        Episode(name:"AKA Ain't We Got Fun", binged: false),
        Episode(name:"AKA Shark in the Bathtub, Monster in the Bed", binged: false),
        Episode(name:"AKA Pork Chop", binged: false),
        Episode(name:"AKA Three Lives and Counting", binged: false),
        Episode(name:"AKA Pray for My Patsy", binged: false),
        Episode(name:"AKA Playland", binged: false)
        ],
        [
        Episode(name:"A.K.A The Perfect Burger", binged: false),
        Episode(name:"A.K.A You're Welcome", binged: false),
        Episode(name:"A.K.A I Have No Spleen", binged: false),
        Episode(name:"A.K.A Customer Service is Standing By", binged: false),
        Episode(name:"A.K.A I Wish", binged: false),
        Episode(name:"A.K.A Sorry Face", binged: false),
        Episode(name:"A.K.A The Double Half-Wappinger", binged: false),
        Episode(name:"A.K.A Camera Friendly", binged: false),
        Episode(name:"A.K.A I Did Something Today", binged: false),
        Episode(name:"A.K.A Hero Pants", binged: false),
        Episode(name:"A.K.A Hellcat", binged: false),
        Episode(name:"A.K.A A Lotta Worms", binged: false),
        Episode(name:"A.K.A Everything", binged: false)
        ]]),
        Show(name: "Agent Carter", favorite: false, episodes: [
        [
        Episode(name:"Now is Not the End", binged: false),
        Episode(name:"Bridge and Tunnel", binged: false),
        Episode(name:"Time and Tide", binged: false),
        Episode(name:"The Blitzkrieg Button", binged: false),
        Episode(name:"The Iron Ceiling", binged: false),
        Episode(name:"A Sin to Err", binged: false),
        Episode(name:"Snafu", binged: false),
        Episode(name:"Valediction", binged: false)
        ],
        [
        Episode(name:"The Lady in the Lake", binged: false),
        Episode(name:"A View in the Dark", binged: false),
        Episode(name:"Better Angels", binged: false),
        Episode(name:"Smoke & Mirrors", binged: false),
        Episode(name:"The Atomic Job", binged: false),
        Episode(name:"Life of the Party", binged: false),
        Episode(name:"Monsters", binged: false),
        Episode(name:"The Edge of Mystery", binged: false),
        Episode(name:"A Little Song and Dance", binged: false),
        Episode(name:"Hollywood Ending", binged: false)
        ]]),
        Show(name: "The Defenders", favorite: false, episodes: [[
        Episode(name:"The H Word", binged: false),
        Episode(name:"Mean Right Hook", binged: false),
        Episode(name:"Worst Behavior", binged: false),
        Episode(name:"Royal Dragon", binged: false),
        Episode(name:"Take Shelter", binged: false),
        Episode(name:"Ashes, Ashes", binged: false),
        Episode(name:"Fish in the Jailhouse", binged: false),
        Episode(name:"The Defenders", binged: false)
        ]]),
        Show(name: "Luke Cage", favorite: false, episodes: [
        [
        Episode(name:"Moment of Truth", binged: false),
        Episode(name:"Code of the Streets", binged: false),
        Episode(name:"Who's Gonna Take the Weight?", binged: false),
        Episode(name:"Step in the Arena", binged: false),
        Episode(name:"Just to Get a Rep", binged: false),
        Episode(name:"Suckas Need Bodyguards", binged: false),
        Episode(name:"Manifest", binged: false),
        Episode(name:"Blowin' Up the Spot", binged: false),
        Episode(name:"DWYCK", binged: false),
        Episode(name:"Take It Personal", binged: false),
        Episode(name:"Now You're Mine", binged: false),
        Episode(name:"Soliloquy of Chaos", binged: false),
        Episode(name:"You Know My Steez", binged: false)
        ],
        [
        Episode(name:"Soul Brother #1", binged: false),
        Episode(name:"Straighten It Out", binged: false),
        Episode(name:"Wig Out", binged: false),
        Episode(name:"I Get Physical", binged: false),
        Episode(name:"All Souled Out", binged: false),
        Episode(name:"The Basement", binged: false),
        Episode(name:"On and On", binged: false),
        Episode(name:"If It Ain't Rough, It Ain't Right", binged: false),
        Episode(name:"For Pete's Sake", binged: false),
        Episode(name:"The Main Ingredient", binged: false),
        Episode(name:"The Creator", binged: false),
        Episode(name:"Can't Front On Me", binged: false),
        Episode(name:"They Reminisce Over You", binged: false)
        ]])
        ]
}
